const Config = {
  GOOGLE_SCOPES : process.env.NEXT_PUBLIC_GOOGLE_SCOPES,
  GOOGLE_CLIENT : process.env.NEXT_PUBLIC_GOOGLE_CLIENT,
  BELAJARIAH_MAIN_SERVICE : process.env.NEXT_PUBLIC_BELAJARIAH_MAIN_SERVICE,
  PAYMENT_GATEWAY_ENDPOINT : process.env.NEXT_PUBLIC_PAYMENT_GATEWAY_ENDPOINT,
  PAYMENT_GATEWAY_USERNAME : process.env.NEXT_PUBLIC_PAYMENT_GATEWAY_USERNAME,
  BELAJARIAH_SERVICE_ENDPOINT : process.env.NEXT_PUBLIC_BELAJARIAH_SERVICE_ENDPOINT,
  ATTACHMENT_SERVICE_ENDPOINT : process.env.NEXT_PUBLIC_ATTACHMENT_SERVICE_ENDPOINT,
}

export { Config }